# Generated by Django 4.0.3 on 2022-04-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolhost', '0002_vehicle_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_register',
            name='Vehical_Type',
        ),
    ]
