# Generated by Django 4.0.3 on 2022-04-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolhost', '0003_remove_vehicle_register_vehical_type'),
        ('siteadmin', '0002_vehicle_type_delete_vehicaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_register',
            name='Vehicle_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteadmin.vehicle_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
