# Generated by Django 4.0.3 on 2022-04-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolhost', '0004_vehicle_register_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Type', models.CharField(max_length=20)),
                ('vehiclename', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_register',
            name='Vehicle_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolhost.vehicletype'),
        ),
    ]
