# Generated by Django 4.0.3 on 2022-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.CharField(max_length=30)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
