# Generated by Django 4.0.3 on 2022-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolhost', '0003_remove_vehicle_register_vehical_type'),
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicletype', models.CharField(max_length=20)),
                ('vehiclename', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='VehicalType',
        ),
    ]
