# Generated by Django 4.0.3 on 2022-04-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolhost', '0005_vehicletype_alter_vehicle_register_vehicle_type'),
        ('siteadmin', '0002_vehicle_type_delete_vehicaltype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_Type',
        ),
    ]
